# Matrices in Tensorflow

In [8]:
import tensorflow as tf
import numpy as np
sess = tf.Session()

## Creating Matrix

In [12]:
identity_matrix = tf.diag([1.0,1.0,1.0])
print(sess.run(identity_matrix))

A = tf.truncated_normal([2, 3])
print(sess.run(A))

B = tf.fill([2,3], 5.0)
print(sess.run(B))

C = tf.random_uniform([3,2])
print(sess.run(C))

D = tf.convert_to_tensor(np.array([[1., 2., 3.],[-3., -7.,-1.],[0., 5., -2.]]))
print(sess.run(D))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[-0.5347915   1.6674278  -0.6896113 ]
 [ 1.0816272   0.43402067  0.7176254 ]]
[[5. 5. 5.]
 [5. 5. 5.]]
[[0.9002396  0.6551744 ]
 [0.43022883 0.1823852 ]
 [0.58154917 0.38621247]]
[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]


## Matrix Operations : Addition/Subtraction

In [15]:
print (sess.run(A+B))
print (sess.run(B-B))

[[4.221401  4.42417   5.7030435]
 [5.07083   5.6490197 5.374395 ]]
[[0. 0. 0.]
 [0. 0. 0.]]


## Matrix Operations : Multiplication

In [17]:
mul = sess.run(tf.matmul(B, identity_matrix))
print (mul)

[[5. 5. 5.]
 [5. 5. 5.]]


## Matrix Operations : Transpose

In [21]:
transpose = sess.run(tf.transpose(B))
print (transpose)

[[5. 5.]
 [5. 5.]
 [5. 5.]]


## Matrix Operations : Determinant

In [24]:
det = sess.run(tf.matrix_determinant(D))
print (det)

-37.99999999999999


## Matrix Operations : Inverse

In [26]:
inv = sess.run(tf.matrix_inverse(D))
print (inv)

[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]
